### ISSUE TITLE
RFC14: Semantics for "^" operator

### ISSUE THREAD

**Issue by dongahn** [flux-framework/rfc#117]
```yaml
    count:
      min: 2
      max: 64
      operator: "^"
      operand: 4
```

If the count specification is given like above, what should be the valid counts between 2-64? Would it be 2, 4, 16, and 64? Or 4, 16 and 64. It think it should be the latter. But I thought I should ask. Also, it may be good to add a clarification sentence in this RFC.
