### ISSUE TITLE
rfc14: stdout/stderr redirection attribute

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/rfc#146]
Not sure if this is something we want to document in RFC14 or leave up to individual implementations, but where do we want to put the paths for stdout and stderr redirection?  My initial thought was under the `attributes` key for each task:

```yaml
tasks
- command: md-simulation.exe
  slot: compute
  count: {total: 1}
  attributes:
    stdout: /path/to/sim.out
    stderr: /path/to/sim.err
- command: database.exe
  slot: data
  count: {total: 1}
  attributes:
    stdout: /path/to/db.out
    stderr: /path/to/db.err
```

If we decide that this is too low of a level of detail for RFC14, we should document the specific attributes supported by flux-core somewhere in the flux-core repo.
