### ISSUE TITLE
need to document minimal jobspec (V1)

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/rfc#149]
We still need to decide on how to document this (wiki vs rfc).  If we go the RFC route, my suggestion would be to do something along the lines of: RFC 14.1 documents version 1 of the jobspec and RFC 14.2 documents version 2 of the jobpsec, etc.  Rather than having the various jobspec versions each get an entirely different RFC number.

Just to document what we have so far.  The version we had on the whiteboard looked like
```yaml
version: 1
resources:
  - type: node
    count: ... # positive integer
    with:
      - type: slot
        count: ... # positive integer
        label: task
        with:
          - type: core
            count: ... # positive integer
tasks:
  - command: ... # array w/ command and args
    slot: task
    count:
      per_slot: ... # positive integer
attributes:
  system:
    duration: days-hours:minutes:seconds # SLURM-style walltime specification
```

where the `node` resource is optional, the ordering of the resource types is fixed (i.e., `[node->]slot->core`), only 1 slot is allowed, only 1 command is allowed, and only `per_slot` is supported for task count.  #146 discusses some additional attributes that could be added.

**Comment by dongahn** [comment]
@SteVwonder: BTW, with this type of RFC, we need to add an option to the resource matching service for hwloc reader to filter out resource types other than core type. IOW, we should only populate `cluster[1]->nodes[N]->core[M]` during reading hwloc data.

**Comment by grondo** [comment]
I guess the only reason to serially number RFCs is so you know the strict ordering in which the RFCs were proposed/merged. I'm guessing that isn't too important here, and it seems like we tend to rewrite RFCs instead of deprecating older RFCs with newer, so we're not adhering to the RFC process anyway.

I'd be fine with a Wiki, but it seems like if we are going to give the minimal jobspec a version number, users will want to be able to go back and see what comprised each version, which is why I proposed and slightly prefer an "RFC" even if it is minimal (at least once the format is fully spec'd.)

**Comment by SteVwonder** [comment]
> ith this type of RFC, we need to add an option to the resource matching service for hwloc reader to filter out resource types other than core type

Good point. I'll open a ticket in flux-sched to track that problem.

**Comment by garlick** [comment]
Crazy idea:  what if we open an issue on jobspec version 2, reference a current git snapshot of RFC 14 from it, and then turn RFC 14 into the version 1 specification?

Also, the examples in RFC 14 (and our test input in flux-core) all claim version 1 so we'll need to do something about that once version 1 is defined.

> I guess the only reason to serially number RFCs is so you know the strict ordering in which the RFCs were proposed/merged. I'm guessing that isn't too important here, and it seems like we tend to rewrite RFCs instead of deprecating older RFCs with newer, so we're not adhering to the RFC process anyway

Here's the zeromq RFC page, which shows how they use serial RFC numbering combined with a "status":   https://rfc.zeromq.org/ (see sidebar, note different ZMTP versions for example).

Since we haven't made a stable release of our code yet (major version 1), I think it's fine for most of our RFCs to be in "raw" or "draft" state, where changes are still possible.  For example we've changed our lowest level wire protocol in RFC 3 several times and still called it version 1 because we don't have to interoperate with older versions.  At some point we'll have to do a version 2 of that one, and possibly interoperate, or at least detect and fail version 1.  While version 2 will be an evolution of version 1, making it a hierarchy would be problematic since we may eventually want to get rid of version 1.

For jobspec, creating a hierarchy off RFC 14 might be OK but it does beg the question of what happens when something in RFC 14 needs to change?  Do we just keep it in "raw" state and only evolve the status of its children?  What happens when something in 14 is not consistent with 14.1?

My vote is to keep the numbering flat.

**Comment by grondo** [comment]
> Crazy idea: what if we open an issue on jobspec version 2, reference a current git snapshot of RFC 14 from it, and then turn RFC 14 into the version 1 specification?

This is a great idea if it gets us moving forward. I don't have a problem with keeping RFC14 as our full-featured (maximal?) jobspec and create new, future RFCs that define several subsets or minimal jobspecs as we work toward full support of our original design, though. If anything, the git history of the current spec would possibly prove useful until we replaced it with the minimal jobspec text.

> Also, the examples in RFC 14 (and our test input in flux-core) all claim version 1 so we'll need to do something about that once version 1 is defined.

This is a real problem now that we're trying to work with actual jobspec in code. We need to do something about those examples, *or* change the `version` key to a floating point number and call the minimal jobspec `0.1` (alternately a dictionary like `"version": { "major": 0, "minor", 1 }`). Then we can work toward "full version 1 support", instead of targeting an unknown integer >1 for full support.

**Comment by grondo** [comment]
> ```
>   attributes:
>   system:
>      duration: days-hours:minutes:seconds # SLURM-style walltime specification
> ```

I'm starting to work with the `duration` field of the minimal jobspec, and it is clear that on the jobspec *reader* side, it would be much easier if the `duration` field was a number representing the walltime limit in seconds (with optional microsecond precision as we have used in other duration/time specs)

Would anyone be opposed to making this change? I guess the drawback is the duration won't be as easily human readable in the raw jobspec.

**Comment by grondo** [comment]
Actually we could increase both ease of parsing *and* readability if we allowed `duration` to be a string with the same format as GNU `sleep(1)`, i.e.

>  `NUMBER[SUFFIX]` - Duration in `NUMBER` seconds. `SUFFIX` may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days. `NUMBER` may be an arbitrary floating point number.

Slurm-style duration as above is easily converted to this format, though for flux tools the `sleep(1)` syntax is much more user-friendly IMO.

**Comment by dongahn** [comment]
Yes this really is a good idea! I only support the number of seconds in the resource matching service for now anyway.

**Comment by SteVwonder** [comment]
While discussing https://github.com/flux-framework/flux-sched/pull/467, we realized that the current proposed V1 jobspec does not include GPUs.  So as a strawman, would it work to stick them under the slot alongside CPUs?  

```yaml
version: 1
resources:
  - type: node
    count: ... # positive integer
    with:
      - type: slot
        count: ... # positive integer
        label: task
        with:
          - type: core
            count: ... # positive integer
          - type: gpu
            count: ... # positive integer
tasks:
  - command: ... # array w/ command and args
    slot: task
    count:
      per_slot: ... # positive integer
attributes:
  system:
    duration: string # GNU sleep(1) format: NUMBER[SUFFIX]
```
