### ISSUE TITLE
RFC14: Add `environment` key to jobspec

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/rfc#188]
My proposal is to add it under the `attributes` key in the `tasks` list.  Thus, each task in the jobspec can have it's own environment. I'm guessing it is easiest to have it as a dictionary with the env variable name as the key and the environment variable value as the value, but I can also see representing it as a large string.

It could also potentially go under the `system` key in the top-level `attributes` section.  This would place it alongside `duration` and apply to every task in the jobspec.  In the name of simplicity and explicitness, I'm thinking that it is better to have it in the `tasks` list.  This way, each task can have a different environement, and we don't have to deal with reconciling the two "layered" environments.  As with other design decisions around jobspec, we can always make a higher-level, more concise format that compiles down into the more verbose jobspec.  On the other hand, having the same environment duplicated in every task will get big, quick.

Thoughts?

Example:
```yaml

version: 1
resources:
  - type: node
    count: 4
    with:
      - type: slot
        count: 1
        label: default
        with:
          - type: core
            count: 2
tasks:
  - command: app
    slot: default
    count:
      per_slot: 1
    attributes:
      environment:
        PATH: "/foo/bar:/john/paul:/george/ringo"
        PS1: ">"
        HOME: "/home/sherbein"
attributes:
  system:
    duration: 3600.
```
