### ISSUE TITLE
Clarify satisfaction of OpenMP-style dependencies in RFC 26

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/rfc#294]
The OpenMP-style dependencies introduced in [RFC 26](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_26.html) don't specify how they are satisfied---whether it is after a job enters state RUN or INACTIVE or after the job enters state INACTIVE with a successful result. It would be great if the satisfaction could be customized, like:

```yaml

- type: inout
  scope: user
  scheme: string
  value: foo
  satisfied: afterany
```
