### ISSUE TITLE
Question: why jobspec -> tasks?

### ISSUE THREAD

**Issue by vsoch** [flux-framework/rfc#370]
I'm doing some thinking about the Jobspec, and have a simple question. Why is the section (for what I'd call jobs) labeled tasks? https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_25.html#tasks. E.g., if I look at this jobspec:

```yaml
    version: 1
    resources:
      - type: node
        count: 4
        with:
          - type: slot
            count: 1
            label: myslot
            with:
              - type: core
                count: 1
    tasks:
      - command: [ "hostname" ]
        slot: myslot
        count:
          total: 5
    attributes:
      system:
        duration: 3600.
        cwd: "/home/flux"
        environment:
          HOME: "/home/flux"
```
This would be akin to (without the details) running:

```console
$ flux submit hostname
$ flux submit hostname
$ flux submit hostname
$ flux submit hostname
$ flux submit hostname
```
Right? Would the above be considered 5 separate submits or a batch job? And then add on the bells and whistles for the cwd, environment variables (which I guess have to be the same for each of the 5 submits?) I'm wondering also because I think it would be good if the spec file can support submit with batch and just submit, and I want to understand how it works to grep that.

Intuitively, when I see a yaml file like this for flux, I would look for "jobs" to coincide with a section of commands for my jobs. Resources makes sense alongside that, and attributes seems kind of random (and it seems not ideal that they have to be globally applied to all jobs, but maybe I just don't understand the spec well enough yet). 

Is there a big dump of jobspec files somewhere I can look at? E.g., more complex ones? Eventually after we are able to support:

```bash
$ flux submit -f jobspec.yaml
```
We can have an entire repository with these files just showing specific examples. And if we can do this well, I can get this same spec to be what plugs in to flux-cloud so I don't need to have two different specs, and a user doesn't need to write two things to run on HPC vs. the Flux Operator (via flux-cloud).

Thanks for answering my bad questions!
