### ISSUE TITLE
Capture/Define storage use cases in the jobspec RFC

### ISSUE THREAD

**Issue by dongahn** [flux-framework/rfc#54]
Creating an issue ticket to capture some of the storage use cases in our jobspec RFC. Once we develop good understandings on this topic, we should create a PR. Moving the existing discussion thread from PR #52 to below.

**Comment by dongahn** [comment]
From @SteVwonder:

For a simple storage use-case, maybe something similar to the request for a specific amount of memory (with the exact location of the disk resources (i.e., burst buffer (BB) & parallel file system (PFS)) depending on their locations within the resource hierarchy).  In this example, I assume that the PFS is the root of the resource tree and the on-node BBs are located under the compute nodes, as siblings to the on-node memory.

``` yaml
version: 1
walltime: 1h
resources:
  - type: parallel-file-system
    amount: 1TB
    with:
    - type: node
      with:
        - type: memory
          amount: 4GB
        - type: burst-buffer
          amount: 200GB
```

Some questions I had while writing this example:

1. Can types have spaces in the name (e.g., parallel file system)?
2. How would you simultaneously request capacity and bandwidth on a PFS/BB?
3. If a center has multiple Lustre file systems and multiple GPFS file systems, how would the user specify that they want one type of PFS over the other (e.g., prefer Luster over GPFS) without limiting the jobspec to a single PFS or explicitly listing all of the Lustre filesystems as potential matches (e.g, how to avoid writing something like `lscratcha OR lscratchb OR lscratchc OR lscratchd OR lscratche OR lscratchf`)?


Also, just a note on a more advanced storage use-case (this doesn't need to be solved immediately, but I figured I would bring it up since it will be an important use-case in the future for not only storage but also network bandwidth and power).  After speaking with @dongahn the other day about burst buffer systems, it would be nice to have the ability to specify a job that has X GBs of space in the BB for staging-in data from the parallel filesystem and then X+Y GBs of space in the BB for actually running the user's app (since additional space will be needed for new checkpoints, etc).  When I thought about how to write this in the current jobspec, three ideas came to mind.

1. This information could be provided in the `properties.user` dictionary of a jobspec as two separate values, one for stage-in and one for execution.  A "BB-aware" scheduler could explicitly look for these values in the `properties.user` dictionary and then schedule the job according to some special BB logic. To me, this is a simple, straightforward way to do it.
2. The initial jobspec could request only X GBs of space, and then once the stage-in is complete, the job/user app could request additional space on the BB as needed via the dynamic scheduling interface.  The main problem here is that the job is never guaranteed to actually receive any additional capacity.
3. The jobspec could add support for time as a dimension in the `count`/`amount` fields.  Then malleable/evolving schedulers could take advantage of this additional knowledge, and rigid schedulers could just use the max of the `count`/`amount` fields.

**Comment by dongahn** [comment]
From @dongahn:

### Existing BB implementations and high level considerations

Given the importance of the burst buffer resources for future systems, I propose our canonical jobspec covers some of the basic burst buffer use cases. Here are a few criteria I think we should consider. Our canonical jobspec should be able to

1. express burst buffer requirements for at least two different emerging implementations and various storage access modes of them: 
    - Node-local NVRAM (our Sierra) implementation with node visibility
    - Intermediate  BB nodes ([Cray's DataWarp](http://docs.cray.com/books/S-2558-5204/S-2558-5204.pdf)) with stripped access mode (job-level BB filesystem mount and visibility)
    - Intermediate  BB nodes (Cray's DataWarp) with private access mode (node-level mount/visibility)

2. express requirements for BB capacity, file sets that need to be staged in and out, and bandwidth

3. express the capacity requirements in a multi-staged fashion, the information essential for the scheduler to overlap the job's stage-in phase with the currently running jobs on the target nodes

### Expressing a BB location in a jobspec's resource hierarchy seems natural

It seems we can do item 1 quite easily with the current jobspec 

For node-local implementation and BB nodes implementation in private mode:
```yml
resource:
  - type: node
    count:
        min: 4
    with:
      - type: bb
```

For BB nodes implementation in striped mode (all of the allocated nodes commonly access the BB file system instance):
```yml
resource:
  - type: node
    count:
        min: 4
  - type: bb
```

### Capacity and staging fileset specification

#### fileset as resources
Capacity, staging file sets, and bandwidth requirements can use more discussions. First to describe the staging requirements, my first attempt is to treat the staging file sets as the resources and hang them under the burst buffer resource

```yml
resource:
  - type: node
    count:
        min: 4
    with:
      - type: bb
        with:
          - type: stage-in
            files: 
              - /lscratchb/user1/cr2.$rank
              - /lscratchb/user1/cr3.$rank
          - type: state-out
            files: 
              - /lscratchb/user1/cr100.$rank
              - /lscratchb/user1/cr101.$rank
```

$rank or some built-in variables would be needed for the spec to express per-node files to stage. I used `files` to as the key to describe the staging files as a list of files. But one can also introduce `dirs` and `flistfile` as alternative ways to describe the staging files. 

For BB nodes implementation in striped mode, all of the files that the job as a whole can be described in the same manner. 

#### Capacity spec
To describe the capacity requirements, we at least need to specify two quantifies: the storage requirement for the stage-in phase and the running phase. The former is typically smaller in size than the latter, and hence this should help the scheduler to overlap the stage-in phase with the currently running jobs' computation or stage-out phase. My first attempt, which I don't yet like:


```yml
resource:
  - type: node
    count:
        min: 4
    with:
      - type: bb
        count:
            min: 20GB
        with:
          - type: stage-in
             count:
                min: 10GB
             files:
                -  /lscratchb/user1/cr2.$rank
```

I can imagine we can also:

```yml
resource:
  - type: node
    count:
        min: 4
    with:
      - type: bb
        count:
            min: 10GB
            max: 20GB
        with:
          - type: stage-in
             files:
                -  /lscratchb/user1/cr2.$rank
``` 

But my mind doesn't easily translate this as 10GB for stage-in and 20GB for running. 

#### Bandwidth spec
For bandwidth requirements, I think for now we only need to be able to specify the bandwidth between the BB layer and the PFS. (We treat CN to BB as a highway)

But even then, I'm not sure how to express this yet. I have to think my trouble is because I don't fully understand how general graph works in our jobspec yet. Perhaps we can use this as an example to show how to specify resource requirement in a general graph. 

In any case, I have to think that IO-bandwidth awareness can help increase resource utilization when we schedule jobs to overlap jobs' stage-in operations with the existing jobs. BB-PFS bandwidth awareness can allow our scheduler to delay stage-in operations as late as possible and help avoid early node locking of jobs.
