### ISSUE TITLE
rfc14: Invalid count range representation in use case 1.2

### ISSUE THREAD

**Issue by morrone** [flux-framework/rfc#86]
Use Case 1.2 does the following:

```
resources:
  - type: node
    count: "[3:30]"
```

This range representation does not appear to be valid according to the jobspec definition.

**Comment by grondo** [comment]
This should definitely be fixed. The `"[min:max]"` format was shorthand discussed in the original "job shape" issue, but we decided to leave all shorthand, syntax sugar, etc out of the rfc, and this example was likely missed at the time.

Should be like this I think:
```
resources:
  - type: node
    count:
      - min: 3
      - max: 30
```
